version: "3"
services:
  server:
    container_name: server
    build:
      context: ./BE/Talktopia/talktopia
      args:
        SERVER_MODE: prod
    ports:
        - 10001:8000
    environment:
        - TZ=Asia/Seoul
  nginx:
    container_name: nginx
    build: ./.nginx
    depends_on:
      - server
    volumes:
      - .nginx/conf.d:/etc/nginx/conf.d
      - .nginx/zerossl:/var/www/zerossl/.well-known/pki-validation
      - .nginx/cert:/cert
    ports:
      - 8080:80
      - 443:443
