# application.yml
server:
  port: 8000
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: ssafy
    key-store-type: PKCS12

# Spring
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://talktopia.site:50000/talktopia?useSSL=false&serverTimezone=UTC&useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: q1w2e3r4
  profiles:
    include:
      - aws
      - credentials
  # JPA
  jpa:
    hibernate:
      ddl-auto: update
      # (create / create-drop / update / validate)

    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  #NaverMail
  mail:
    username: wbo1026@naver.com
    password: QuddnR1026!

  # JWT
  security:
    jwt:
      secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa
  redis:
    host: talktopia.site
    port: 6379
    password: q1w2e3r4
# log level
logging:
  level:
    root: INFO

# OpenVidu
openvidu:
  url: https://talktopia.site:8443/
  secret: root

cloud:
  aws:
    s3:
      bucket: talktopia
    region:
      static: ap-northeast-2 #Asia Pacific -> seoul
    stack:
      auto: false
    credentials:
      access-key: AKIAUEUEPWDIUDY33S2W
      secret-key: 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
servlet:
  multipart:
    enabled: true
    max-file-size: 20MB
    max-request-size: 20MB
